# -*- coding: utf-8 -*-
"""Predictive model by Sckl.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126o5dHpNQBPIS7gdncR8KAmSfPaYpfeh
"""

!pip install scikit-learn pandas numpy

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

data = {
    "message": [
        "Congratulations! You have won a lottery",
        "Call me when you are free",
        "Limited offer! Buy now",
        "Meeting scheduled at 10 AM",
        "Win cash prizes instantly",
        "Let’s catch up tomorrow",
        "Urgent! Your account is compromised",
        "Happy birthday, have a great day",
        "Exclusive deal just for you",
        "Project deadline is next week"
    ],
    "label": [
        "spam", "ham", "spam", "ham", "spam",
        "ham", "spam", "ham", "spam", "ham"
    ]
}
df = pd.DataFrame(data)
df

X = df["message"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

vectorizer = TfidfVectorizer(stop_words="english")
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

y_pred = model.predict(X_test_tfidf)
y_pred

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

confusion_matrix(y_test, y_pred)

new_emails = [
    "Congratulations, you won a free gift card",
    "Please review the attached project report"
]

new_emails_tfidf = vectorizer.transform(new_emails)
predictions = model.predict(new_emails_tfidf)

for email, label in zip(new_emails, predictions):
    print(f"Email: {email}")
    print(f"Prediction: {label}")
    print()