# -*- coding: utf-8 -*-
"""Wheatherapi CodeTech

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KaCEM56_SmjbejCFlOgVCY12KKSrULWf
"""

import requests
import matplotlib.pyplot as plt
API_KEY = "a63e08c8ca3acb22912dc03f72098659"
CITY = "Nellore,IN"
url = f"https://api.openweathermap.org/data/2.5/forecast?q={CITY}&appid={API_KEY}&units=metric"
response = requests.get(url)
if response.status_code != 200:
    print("Error fetching data:", response.json())
    exit()
data = response.json()
Dates = []
Temperature = []
for item in data.get("list", []):
    Dates.append(item["dt_txt"])
    Temperature.append(item["main"]["temp"])
plt.figure(figsize=(10, 5))
plt.plot(Dates[:10], Temperature[:10], marker='o')
plt.xticks(rotation=45)
plt.title("Temperature Forecast for Nellore")
plt.xlabel("Date & Time")
plt.ylabel("Temperature (°C)")
plt.tight_layout()
plt.show()